### ISSUE TITLE
IllegalStateException : When Item Count is 0 on Search Implementation

### ISSUE THREAD

**Issue by meethdjain** [edsilfer/sticky-index#16]
Hi @edsilfer ,

Thank you for developing this library.

I'm using the libary along with Search Funtionality, whenever the list count is 0.
I'm getting the following IllegalStateException 

java.lang.IllegalStateException: firstVisibleView must not be null

Anyway of fixing around this ?

Let me know if any other details are required.

StackTrace : 

04-21 22:38:01.038 1893-1893/E/AndroidRuntime: FATAL EXCEPTION: main
                                                            PID: 1893
                                                            java.lang.IllegalStateException: firstVisibleView must not be null
                                                                at br.com.stickyindex.view.StickyIndexLayoutManager.synchronizeScrolls(StickyIndexLayoutManager.kt:31)
                                                                at br.com.stickyindex.view.StickyIndexLayoutManager.update(StickyIndexLayoutManager.kt:41)
                                                                at br.com.stickyindex.view.StickyIndex$bindRecyclerView$1.onScrolled(StickyIndex.kt:68)
                                                                at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4844)
                                                                at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3909)
                                                                at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3540)
                                                                at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
                                                                at android.view.View.layout(View.java:19692)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:6057)
                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1780)
                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1546)
                                                                at android.view.View.layout(View.java:19692)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:6057)
                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                at android.view.View.layout(View.java:19692)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:6057)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                at android.view.View.layout(View.java:19692)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:6057)
                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                at android.view.View.layout(View.java:19692)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:6057)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                at android.view.View.layout(View.java:19692)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:6057)
                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                                                                at android.view.View.layout(View.java:19692)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:6057)
                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                at com.android.internal.policy.DecorView.onLayout(DecorView.java:759)
                                                                at android.view.View.layout(View.java:19692)
                                                                at android.view.ViewGroup.layout(ViewGroup.java:6057)
                                                                at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2515)
                                                                at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2224)
                                                                at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1410)
                                                                at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6834)
                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:778)
                                                                at android.view.Choreographer.doFrame(Choreographer.java:713)
                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
                                                                at android.os.Handler.handleCallback(Handler.java:789)
                                                                at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                at android.os.Looper.loop(Looper.java:164)
                                                                at android.app.ActivityThread.main(ActivityThread.java:6809)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by edsilfer** [comment]
Hi @meethdjain , I'm afraid I need more details of your situation. Check the [code below](https://github.com/edsilfer/sticky-index/blob/master/library/src/main/java/br/com/stickyindex/view/StickyIndexLayoutManager.kt):

```kotlin
 /**
     * Must be called every time the reference {@link RecyclerView} scrolls. This method redraws the
     * state of the sticky letters
     */
    fun update(rv: RecyclerView, dy: Float) {
        if (contentList.adapter.itemCount < 2) return
        synchronizeScrolls(rv)
        val firstVisibleItemContainer = contentList.getChildAt(0)
        val firstVisibleItem = firstVisibleItemContainer.findViewById<TextView>(R.id.sticky_row_index)
        displayHeader(firstVisibleItem)
        val nextVisibleItem = contentList.getChildAt(1).findViewById<TextView>(R.id.sticky_row_index)
```

^ this is were this stack trace you posted is coming from. `contentList` is the list containing the headers, if you got to line 31, as the st says, it means there are contents there. However, the contents of it doesn't  seems to have `R.id.sticky_row_index`. Are you sure you are adding the correct element in the UI when filtering the list? Can you specifically describe what you're doing? It doesn't look like a problem in the library since it takes care of the situation of having 2 or lesse items in the list as shown in ` if (contentList.adapter.itemCount < 2) return`

**Comment by meethdjain** [comment]
@edsilfer 
Thanks, found the issue.

I wasn't calling stickyIndex.refresh(indexes); in case of Empty List.
Thanks for the quick reply
